#pragma once
#include <Windows.h>
#include <WinUser.h>
#include <thread>
#include <iostream>
#include <string>
#include <Psapi.h>
#include <TlHelp32.h>
#include <lmcons.h>
#include <vector>
#include <filesystem>
#include <fstream>